# Generated by Django 6.0.2 on 2026-02-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=10000)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificao', models.DateField(auto_now=True)),
            ],
        ),
    ]
