# Generated by Django 6.0.2 on 2026-02-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='data_modificao',
            new_name='data_modificacao',
        ),
    ]
