# Generated by Django 6.0.2 on 2026-02-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_data_modificao_pokemon_data_modificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='data_criacao',
            new_name='data_criacacao',
        ),
    ]
