# Generated by Django 6.0.2 on 2026-02-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_data_criacao_pokemon_data_criacacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=10000)),
                ('data_criacacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateField(auto_now=True)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
    ]
